
-- +migrate Up
CREATE TABLE IF NOT EXISTS users (
  id int(15) AUTO_INCREMENT,
  name VARCHAR(255),
  email VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
  );
    
-- +migrate Down
DROP TABLE IF EXISTS users;