apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-next
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: takedock/go-next_api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        command: ["go", "run", "main.go"]
        envFrom:
        - configMapRef:
            name: go-config
        ports:
        - containerPort: 8080

